FROM node:22-bookworm-slim

WORKDIR /app

RUN apt-get update \
	&& apt-get install -y --no-install-recommends ca-certificates curl git \
	&& rm -rf /var/lib/apt/lists/*

RUN git clone --depth 1 https://github.com/israelmeinert/tech-challenge-2.git /app
RUN npm install

EXPOSE 3000

CMD ["npm", "run", "dev"]