import { FinanceModel } from "./types";

export const data: FinanceModel = {
  id: 1,
  name: "Ana Marcela",
  totalBalance: "17373.15",
  extract: [
    {
      id: 1,
      category: "Salário",
      type: "INCOME",
      description: "Salário de janeiro",
      amount: "6200.00",
      date: "01/01/2026",
    },
    {
      id: 2,
      category: "Casa",
      type: "EXPENSE",
      description: "Aluguel",
      amount: "1850.00",
      date: "03/01/2026",
    },
    {
      id: 3,
      category: "Alimentação",
      type: "EXPENSE",
      description: "Mercado da semana",
      amount: "412.80",
      date: "03/01/2026",
    },
    {
      id: 4,
      category: "Casa",
      type: "EXPENSE",
      description: "Internet",
      amount: "119.90",
      date: "07/01/2026",
    },
    {
      id: 5,
      category: "Lazer",
      type: "EXPENSE",
      description: "Jantar com amigos",
      amount: "168.40",
      date: "11/01/2026",
    },
    {
      id: 6,
      category: "Transporte",
      type: "EXPENSE",
      description: "Uber para o trabalho",
      amount: "230.00",
      date: "15/01/2026",
    },
    {
      id: 7,
      category: "Outros",
      type: "EXPENSE",
      description: "Streaming e assinaturas",
      amount: "44.90",
      date: "18/01/2026",
    },
    {
      id: 8,
      category: "Outros",
      type: "EXPENSE",
      description: "Farmácia",
      amount: "86.30",
      date: "21/01/2026",
    },
    {
      id: 9,
      category: "Outros",
      type: "INCOME",
      description: "Freelance de revisão",
      amount: "850.00",
      date: "25/01/2026",
    },
    {
      id: 10,
      category: "Outros",
      type: "EXPENSE",
      description: "Mensalidade da academia",
      amount: "129.90",
      date: "28/01/2026",
    },
    {
      id: 11,
      category: "Salário",
      type: "INCOME",
      description: "Salário de fevereiro",
      amount: "6200.00",
      date: "01/02/2026",
    },
    {
      id: 12,
      category: "Casa",
      type: "EXPENSE",
      description: "Aluguel",
      amount: "1850.00",
      date: "03/02/2026",
    },
    {
      id: 13,
      category: "Alimentação",
      type: "EXPENSE",
      description: "Compras no mercado",
      amount: "438.55",
      date: "06/02/2026",
    },
    {
      id: 14,
      category: "Alimentação",
      type: "EXPENSE",
      description: "Cafés e lanches",
      amount: "42.00",
      date: "10/02/2026",
    },
    {
      id: 15,
      category: "Casa",
      type: "EXPENSE",
      description: "Conta de luz e água",
      amount: "214.60",
      date: "10/02/2026",
    },
    {
      id: 16,
      category: "Lazer",
      type: "EXPENSE",
      description: "Date night",
      amount: "215.80",
      date: "10/02/2026",
    },
    {
      id: 17,
      category: "Transporte",
      type: "EXPENSE",
      description: "Passagens e corridas",
      amount: "228.40",
      date: "17/02/2026",
    },
    {
      id: 18,
      category: "Outros",
      type: "INCOME",
      description: "Venda do sofá antigo",
      amount: "300.00",
      date: "20/02/2026",
    },
    {
      id: 19,
      category: "Outros",
      type: "EXPENSE",
      description: "Corte de cabelo",
      amount: "90.00",
      date: "23/02/2026",
    },
    {
      id: 20,
      category: "Lazer",
      type: "EXPENSE",
      description: "Passeio de fim de semana",
      amount: "680.00",
      date: "27/02/2026",
    },
    {
      id: 21,
      category: "Salário",
      type: "INCOME",
      description: "Salário de março",
      amount: "6200.00",
      date: "01/03/2026",
    },
    {
      id: 22,
      category: "Casa",
      type: "EXPENSE",
      description: "Aluguel",
      amount: "1850.00",
      date: "03/03/2026",
    },
    {
      id: 23,
      category: "Alimentação",
      type: "EXPENSE",
      description: "Mercado do mês",
      amount: "455.20",
      date: "05/03/2026",
    },
    {
      id: 24,
      category: "Casa",
      type: "EXPENSE",
      description: "Conta de água",
      amount: "73.15",
      date: "07/03/2026",
    },
    {
      id: 25,
      category: "Lazer",
      type: "EXPENSE",
      description: "Jantar com amigos",
      amount: "198.75",
      date: "10/03/2026",
    },
    {
      id: 26,
      category: "Transporte",
      type: "EXPENSE",
      description: "Recarga do cartão",
      amount: "180.00",
      date: "12/03/2026",
    },
    {
      id: 27,
      category: "Outros",
      type: "INCOME",
      description: "Freelance de conteúdo",
      amount: "1200.00",
      date: "19/03/2026",
    },
    {
      id: 28,
      category: "Casa",
      type: "EXPENSE",
      description: "Material de limpeza",
      amount: "145.60",
      date: "22/03/2026",
    },
    {
      id: 29,
      category: "Lazer",
      type: "EXPENSE",
      description: "Cinema",
      amount: "62.00",
      date: "26/03/2026",
    },
    {
      id: 30,
      category: "Transporte",
      type: "EXPENSE",
      description: "Revisão do carro",
      amount: "540.00",
      date: "29/03/2026",
    },
    {
      id: 31,
      category: "Salário",
      type: "INCOME",
      description: "Salário de abril",
      amount: "6200.00",
      date: "01/04/2026",
    },
    {
      id: 32,
      category: "Casa",
      type: "EXPENSE",
      description: "Aluguel",
      amount: "1850.00",
      date: "03/04/2026",
    },
    {
      id: 33,
      category: "Alimentação",
      type: "EXPENSE",
      description: "Compras do mercado",
      amount: "469.90",
      date: "05/04/2026",
    },
    {
      id: 34,
      category: "Casa",
      type: "EXPENSE",
      description: "Conta de luz",
      amount: "243.80",
      date: "08/04/2026",
    },
    {
      id: 35,
      category: "Lazer",
      type: "EXPENSE",
      description: "Happy hour",
      amount: "154.30",
      date: "12/04/2026",
    },
    {
      id: 36,
      category: "Investimento",
      type: "INCOME",
      description: "Dividendos da carteira",
      amount: "180.45",
      date: "15/04/2026",
    },
    {
      id: 37,
      category: "Outros",
      type: "EXPENSE",
      description: "Consulta médica",
      amount: "220.00",
      date: "24/04/2026",
    },
    {
      id: 38,
      category: "Outros",
      type: "EXPENSE",
      description: "Roupas de trabalho",
      amount: "310.90",
      date: "24/04/2026",
    },
    {
      id: 39,
      category: "Transporte",
      type: "EXPENSE",
      description: "Corridas da semana",
      amount: "96.20",
      date: "24/04/2026",
    },
    {
      id: 40,
      category: "Outros",
      type: "EXPENSE",
      description: "Corte de cabelo",
      amount: "88.00",
      date: "24/04/2026",
    },
    {
      id: 41,
      category: "Salário",
      type: "INCOME",
      description: "Salário de maio",
      amount: "6200.00",
      date: "01/05/2026",
    },
    {
      id: 42,
      category: "Casa",
      type: "EXPENSE",
      description: "Aluguel",
      amount: "1850.00",
      date: "03/05/2026",
    },
    {
      id: 43,
      category: "Alimentação",
      type: "EXPENSE",
      description: "Mercado grande do mês",
      amount: "486.75",
      date: "05/05/2026",
    },
    {
      id: 44,
      category: "Casa",
      type: "EXPENSE",
      description: "Internet",
      amount: "119.90",
      date: "06/05/2026",
    },
    {
      id: 45,
      category: "Presente",
      type: "EXPENSE",
      description: "Presente de Dia das Mães",
      amount: "240.00",
      date: "11/05/2026",
    },
    {
      id: 46,
      category: "Lazer",
      type: "EXPENSE",
      description: "Brunch de domingo",
      amount: "132.60",
      date: "14/05/2026",
    },
    {
      id: 47,
      category: "Outros",
      type: "INCOME",
      description: "Freelance de apresentação",
      amount: "950.00",
      date: "17/05/2026",
    },
    {
      id: 48,
      category: "Transporte",
      type: "EXPENSE",
      description: "Gasolina",
      amount: "210.30",
      date: "20/05/2026",
    },
    {
      id: 49,
      category: "Lazer",
      type: "EXPENSE",
      description: "Show no fim de semana",
      amount: "260.00",
      date: "23/05/2026",
    },
    {
      id: 50,
      category: "Outros",
      type: "EXPENSE",
      description: "Farmácia",
      amount: "68.40",
      date: "25/05/2026",
    },
  ],
};
